version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/src/shortenerTools"
    update_schedule: "weekly"
    default_assignees: "fboucher"
    default_reviewers: "fboucher"
    target_branch: "AZURL78-add-dependabot"
  - package_manager: "dotnet:nuget"
    directory: "/src/adminTools/adminBlazorWebsite\src"
    update_schedule: "weekly"
    default_assignees: "fboucher"
    default_reviewers: "fboucher"
    target_branch: "AZURL78-add-dependabot"