name: DEV CI-CD 

on:
  push:
    branches: dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.GR_azUrlGitHubDev_CREDENTIALS }}
        
    - uses: azure/arm-deploy@v1
      id: deployARM
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.GR_azUrlGitHubDev_CREDENTIALS.subscriptionId }}
        resourceGroupName: UrlShortnerDEV
        deploymentName: github-dev
        template: deployment/azureDeploy.json
        parameters: deployment/azureDeploy.params.dev.json