name: vnext-v3 CI-CD 

on:
  push:
    branches: vnext-v3

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.GR_azUrlGitHubDev_CREDENTIALS }}
        
    - name: Rename local.setting.sexample.json to local.settings.json
      run: mv src/local.settings.example.json src/local.settings.json
       
    - run: |
        az deployment group create -n github-dev -g UrlShortnerDEV --template-file deployment/azureDeploy.json --parameters "deployment/azureDeploy.params.dev.json"
